export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
//UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
//Data reducer types
export const SET_POSTS = "SET_POSTS";
export const LIKE_POST = " LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const DELETE_POST = "DELETE_POST";
export const POST_ERRORS = "POST_ERRORS";
export const POST_POST = "POST_POST";
export const SET_POST = "SET_POST";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
//chat reducer type
export const GET_CHAT = "GET_CHAT";
//movie reducer type

export const GET_UPCOMINGMOVIE = "GET_UPCOMINGMOVIE";
export const GET_MOVIEDETAIL = "GET_MOVIEDETAIL";

// export const GET_TRENDING_MOVIE = "GET_TRENDING_MOVIE";
// export const GET_UPCOMING_MOVIE = "GET_UPCOMING_MOVIE";
// export const GET_TOPRATED_MOVIE = "GET_TOPRATED_MOVIE";
// export const GET_ACTION_MOVIE = "GET_ACTION_MOVIE";
// export const GET_COMEDY_MOVIE = "GET_COMEDY_MOVIE";
// export const GET_HORROR_MOVIE = "GET_HORROR_MOVIE";
// export const GET_ROMANCE_MOVIE = "GET_ROMANCE_MOVIE";
// export const GET_DOCUMENTARY_MOVIE = "GET_DOCUMENTARY_MOVIE";
// export const GET_ADVENTURE_MOVIE = "GET_ADVENTURE_MOVIE";
// export const GET_ANIMATION_MOVIE = "GET_ANIMATION_MOVIE";
// export const GET_DRAMA_MOVIE = "GET_DRAMA_MOVIE";
// export const GET_CRIME_MOVIE = "GET_CRIME_MOVIE";
// export const GET_FAMILY_MOVIE = "GET_FAMILY_MOVIE";
// export const GET_FANTASY_MOVIE = "GET_FANTASY_MOVIE";
// export const GET_HISTORY_MOVIE = "GET_HISTORY_MOVIE";
// export const GET_MUSIC_MOVIE = "GET_MUSIC_MOVIE";
// export const GET_SCIFI_MOVIE = "GET_SCIFI_MOVIE";
// export const GET_TV_MOVIE = "GET_TV_MOVIE";
// export const GET_THRILLER_MOVIE = "GET_THRILLER_MOVIE";
// export const GET_WAR_MOVIE = "GET_WAR_MOVIE";

// //...loading..

// export const LOADING_TRENDING_MOVIE = "LOADING_TRENDING_MOVIE";
// export const LOADING_UPCOMING_MOVIE = "LOADING_UPCOMING_MOVIE";
// export const LOADING_TOPRATED_MOVIE = "LOADING_TOPRATED_MOVIE";
// export const LOADING_ACTION_MOVIE = "LOADING_ACTION_MOVIE";
// export const LOADING_COMEDY_MOVIE = "LOADING_COMEDY_MOVIE";
// export const LOADING_HORROR_MOVIE = "LOADING_HORROR_MOVIE";
// export const LOADING_ROMANCE_MOVIE = "LOADING_ROMANCE_MOVIE";
// export const LOADING_DOCUMENTARY_MOVIE = "LOADING_DOCUMENTARY_MOVIE";
// export const LOADING_ADVENTURE_MOVIE = "LOADING_ADVENTURE_MOVIE";
// export const LOADING_ANIMATION_MOVIE = "LOADING_ANIMATION_MOVIE";
// export const LOADING_DRAMA_MOVIE = "LOADING_DRAMA_MOVIE";
// export const LOADING_CRIME_MOVIE = "LOADING_CRIME_MOVIE";
// export const LOADING_FAMILY_MOVIE = "LOADING_FAMILY_MOVIE";
// export const LOADING_FANTASY_MOVIE = "LOADING_FANTASY_MOVIE";
// export const LOADING_HISTORY_MOVIE = "LOADING_HISTORY_MOVIE";
// export const LOADING_MUSIC_MOVIE = "LOADING_MUSIC_MOVIE";
// export const LOADING_SCIFI_MOVIE = "LOADING_SCIFI_MOVIE";
// export const LOADING_TV_MOVIE = "LOADING_TV_MOVIE";
// export const LOADING_THRILLER_MOVIE = "LOADING_THRILLER_MOVIE";
// export const LOADING_WAR_MOVIE = "LOADING_WAR_MOVIE";
